# coding: utf-8
"""
"""

from __future__ import absolute_import
import sys

try:
    from stbt._vars import _libexecdir  # Generated by 'make install'. pylint:disable=import-error,no-name-in-module
    sys.path.insert(0, _libexecdir + "/stbt")
except ImportError:
    sys.path.insert(0, "DUMMY")  # Importing from source directory

from _@PROJECT@.toolbox import demo
