# coding: utf-8
"""Main stb-tester python module. Intended to be used with `stbt run`.

See `man stbt` and http://stb-tester.com for documentation.

Copyright 2012-2013 YouView TV Ltd and contributors.
Copyright 2013-2015 stb-tester.com Ltd.
License: LGPL v2.1 or (at your option) any later version (see
https://github.com/stb-tester/stb-tester/blob/master/LICENSE for details).
"""

from __future__ import absolute_import

import sys

try:
    from stbt._vars import _libexecdir  # Generated by 'make install'. pylint:disable=import-error,no-name-in-module

    sys.path.insert(0, _libexecdir + "/stbt")
except ImportError:
    sys.path.insert(0, "DUMMY")  # Importing from source directory


from _sc_stbt.core_statemachine import StateMachine
from _sc_stbt.core import detect_many_match, wait_for_many_match, press_until_many_match, wait, \
    get_all_templates_in_directory, fuzzy_match, ocr_until, crop, repeat, get_text, write_csv_file, \
    debug, press, get_generic_template_path, combo_press, write_statut_boot_test, get_statut_boot_test, write_statut_test, get_statut_test, timer, filter_template, write_technical_information, \
    convert_mask_to_regions ,get_timer_value , voice_command , press_voice_command , play_voice_command, is_text, multi_threading
from _sc_stbt.stbts import info, ddebug, any_match, wait_any_match, match_text, get_gray_threshold, get_blackscreen_threshold, _press
from _sc_stbt.zapping import zap_to_channel, zap_up_down,zap_line_up_down, is_live, \
    test_zap_black_screen_on, test_zap_black_screen_off, test_zap_info_banner, \
    read_lcn, zapping, endurance_zapping, zap_two_channel, check_subtitles, get_current_lcn
from _sc_stbt.pyspawn import Spawn
from _sc_stbt.standby_wakeup import is_wakeup, set_wakeup, is_standby, set_standby, _set_wakeup, _set_standby, test_wakeup
from _sc_stbt.menu import menu, navigation
from _sc_stbt.guide import guide
from _sc_stbt.usb_serial import USBserial, set_power_off, set_power_on, set_power, set_hdmi_input , epower
from _sc_stbt.video import video
from _sc_stbt.navigation import parameters, generate_position, target, gototarget
from _sc_stbt.memory_monitoring import get_logs, start_monitoring , plot_mem
from _sc_stbt.getting_traces import  active_traces , get_traces , get_date
from _sc_stbt.youtube_keyboard import youtube_keyboard
from _sc_stbt.netflix_keyboard import netflix_enter_password, netflix_enter_account, netflix_search_movie
from _sc_stbt.amazon_keyboard import amazon_keyboard, amazon_search

from tests.power_on import test_power_on, check_stb_boot
from tests.power_off import test_power_off,test_power_all_off
from tests.power import boot_on, boot_off
#from tests.standby_wakeup import test_standby_wakeup, is_wakeup, set_wakeup, is_standby, set_standby,wait_for_wakeup
from tests.video_tests import video_tests, audio_tests
from tests.youtube_video import test_open_video_youtube, test_youtube_motion, test_youtube_pause, test_youtube_play,\
            test_youtube_fastforward, test_youtube_rewind, test_youtube_next_video, test_youtube_previous_video, \
            test_exit_youtube, navigation_youtube, is_youtube, check_cursor, check_timer, test_navigation_youtube, back_to_youtube_menu
from tests.netflix_video import test_netflix_motion, test_netflix_pause, test_netflix_play, test_netflix_fastforward, \
            test_netflix_rewind, test_netflix_next_video, test_netflix_previous_video, sign_in_netflix, open_video_netflix, \
            sign_out_netflix, test_is_netflix, test_exit_netflix, test_navigation_netflix, goto_config_menu, back_to_netflix_movie_menu, \
            test_switch_profile_netflix, forward_play_netflix, rewind_play_netflix, active_subtitles_netflix, goto_settings_menu, \
            test_close_netflix, test_exit_netflix_by_button_home
from tests.amazon_video import  is_amazon, select_carousel, is_end_list_navigation, navigation_list, open_movie_detail_page, \
            back_to_home, open_library, goto_movies_menu, select_free_video, start_movie, detect_movie, back_to_list, goto_watchlist, \
            test_amazon_motion, count_navigation, quit_amazon, is_add_to_watchlist,add_to_watchlist, search_movie_amazon, open_gerbil,goto_basic_bandwidth, \
    check_state_basic_bandwidth, enable_disable_basic_bandwidth, set_basic_bandwidth, exit_amazon, test_amazon_pause,test_amazon_play,test_amazon_fastforward, \
    test_amazon_rewind,get_error_info,open_catflap, close_interface,stop_script,state_script_check,run_script,goto_gerbil_scripts,open_settings,deregister_your_device,\
    get_signin_code,get_new_signin_code
from tests.search_amazon import search_video_amazon
from tests.signin_amazon import is_amazon_signin, sign_in_amazon, check_keyboard, write_text, goto_cord, _next_key, signin_by_web
from tests.search_youtube import  search_video
from tests.search_netflix import search_netflix
from tests.standby_wakeup import test_force_standby, test_set_standby, test_force_wakeup, test_set_wakeup
from tests.test_audio import check_vol_up ,is_not_audio , is_audio ,  check_vol_down
from tests.cbeebies_video import test_cbeebies_fastforward, test_cbeebies_rewind, test_cbeebies_motion
from tests.quad_reset import reset_quad
from tests.goto_application import go_to_netflix, go_to_youtube, go_to_amazon

__all__ = [
    "detect_many_match",
    "wait_for_many_match",
    "press_until_many_match",
    "wait",
    "get_all_templates_in_directory",
    "fuzzy_match",
    "ocr_until",
    "crop",
    "get_specific_templates_path",
    "repeat",
    "set_hdmi_input",
    "init_precondition",
    "write_csv_file",
    "convert_mask_to_regions"
]
