#!/bin/sh

# Copyright 2012-2013 YouView TV Ltd.
# License: LGPL v2.1 or (at your option) any later version (see
# https://github.com/stb-tester/stb-tester/blob/master/LICENSE for details).

#/ usage: crtmpserver <command>
#/
#/ Available commands are:
#/     start          start crtmpserver
#/     stop           stop crtmpserver

. utils.sh

usage() { grep '^#/' "$0" | cut -c4-; }
[ $# -ge 1 ] || { usage >&2; exit 1; }

rtmpserver() {
	case $1 in
		start)
			# Wait for rtmp server to start up:
			started=false
			for i in $(seq 100); do
				netstat -ln --tcp | grep -q ':1935' && { started=true; Done "RTMP server is running"; break; }
				sleep 0.1
			done
			$started || sudo service crtmpserver restart
			;;
		stop)
			sudo service crtmpserver stop
			;;
	esac
}

rtmpserver $1
