#!/bin/sh

# Copyright 2012-2013 YouView TV Ltd.
# License: LGPL v2.1 or (at your option) any later version (see
# https://github.com/stb-tester/stb-tester/blob/master/LICENSE for details).

#/ usage: stbtv2 [--help] [--version] [--with-experimental] <command> [args]
#/
#/ Available commands are:
#/     stop           Stop crtmpserver and irtrans
#/     run            Run a testcase
#/     batch          Run testcases repeatedly, create html report
#/     auto-selftest  Test your test-cases against saved screenshots
#/     config         Print configuration value
#/     control        Send remote control signals
#/     lint           Static analysis of testcases
#/     match          Compare two images
#/     power          Control networked power switch
#/     record         Record a testcase
#/     screenshot     Capture a single screenshot
#/     tv             View live video on screen
#/     virtual-stb    Configure stbt to use an STB emulator
#/
#/ Experimental commands. These may change in the future in a backwards-
#/ incompatible way. They require passing the '--with-experimental' flag:
#/     camera         Configure stbt to capture video from a TV using a camera
#/
#/ For help on a specific command do 'stbt <command> --help'.
#/ See 'man stbt' for more detailed information.

. utils.sh

usage() { grep '^#/' "$0" | cut -c4-; }
[ $# -ge 1 ] || { usage >&2; exit 1; }

stbtv2 () {
	#echo ">>>>>>>>>>>>> ${STBT_CONFIG_NAME}"
	#set_control "irtrans:/dev/${ttyUSB}:${STBT_CONFIG_NAME}"
	stbt "$@"
	exit_status=$?
	printf "$(bold stbt $@...) "
	case $exit_status in
        0) echo "$(green OK)";;
        #77) status=0; echo "$(yellow SKIPPED)";;
        *) echo "$(red FAIL)";;
	esac
	return $exit_status
}

[[ "$1" == "stop" ]] && { rtmpserver stop; irtrans stop; exit 1; }

stbtv2 "$@"

